### ISSUE TITLE
Outdated Client and Https Issue

### ISSUE THREAD

**Issue by abhij89** [kellan/magpierss#9]
The library doesn't seems to be updated, the client "Snoopy" has already been updated but library is still using the old version. Also library doesn't seems to be fetching "https" feeds, is it http only library?

Can we have a update now?? For http it works very well.

**Comment by Whip** [comment]
I see you updated Snoopy yourself and have a PR open. Did you do something for the https issue as well?

**Comment by abhij89** [comment]
@VeeK727 yes, updated the pull request #10 , please check. Snoopy client was sending the port in the wrong format.
